Use correct assert() method so we get good error messages.
BEFORE:
     AssertionError: expected null to roughly deeply equal undefined

AFTER:
      AssertionError: expected { Object (elements) } to roughly deeply equal { Object (elements) }
      + expected - actual
       {
         "elements": [
           {
      -      "internalValue": "foo"
      +      "internalValue": "tag"
             "typeOrder": 4
           }
         ]
       }